# Generated by Django 6.1 on 2026-09-01 14:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône ou classe CSS", max_length=100, verbose_name='Icône (classe SVG ou nom)')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Courte description')),
                ('description', models.TextField(blank=True, verbose_name='Description complète')),
                ('icon', models.CharField(blank=True, help_text='Code SVG inline ou classe CSS', max_length=200, verbose_name='Icône SVG / classe')),
                ('image', models.ImageField(blank=True, upload_to='services/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_name', models.CharField(default='Abdoulwahab Oumar', max_length=200, verbose_name='Nom du professionnel')),
                ('slogan', models.CharField(blank=True, max_length=300, verbose_name='Slogan')),
                ('short_presentation', models.TextField(blank=True, verbose_name='Courte présentation')),
                ('full_description', models.TextField(blank=True, verbose_name='Description complète')),
                ('phone_primary', models.CharField(default='+237 693 149 222', max_length=50, verbose_name='Téléphone principal')),
                ('phone_secondary', models.CharField(blank=True, default='+237 690 892 646', max_length=50, verbose_name='Deuxième téléphone')),
                ('phone_third', models.CharField(blank=True, default='+237 689 874 206', max_length=50, verbose_name='Troisième téléphone')),
                ('whatsapp_number', models.CharField(default='+237 693 149 222', max_length=50, verbose_name='Numéro WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Adresse')),
                ('city', models.CharField(default='Douala', max_length=100, verbose_name='Ville')),
                ('country', models.CharField(default='Cameroun', max_length=100, verbose_name='Pays')),
                ('profile_photo', models.ImageField(blank=True, upload_to='site/', verbose_name='Photo de profil')),
                ('logo', models.ImageField(blank=True, upload_to='site/', verbose_name='Logo')),
                ('hero_image', models.ImageField(blank=True, upload_to='site/', verbose_name='Image hero')),
                ('hero_text', models.CharField(default='Des solutions pensées pour vos projets.', max_length=300, verbose_name='Texte hero')),
                ('hero_subtext', models.CharField(blank=True, max_length=500, verbose_name='Sous-texte hero')),
                ('seo_title', models.CharField(default='Abdoulwahab Oumar — Ingénieur Civil & Bâtiment | Douala, Cameroun', max_length=200, verbose_name='Titre SEO')),
                ('seo_description', models.TextField(blank=True, verbose_name='Description SEO')),
                ('og_image', models.ImageField(blank=True, upload_to='site/', verbose_name='Image Open Graph')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter / X')),
                ('copyright_year', models.PositiveIntegerField(default=2026, verbose_name='Année de copyright')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Courte description')),
                ('description', models.TextField(blank=True, verbose_name='Description complète')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localisation')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Nom du client')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Durée')),
                ('main_image', models.ImageField(upload_to='projects/main/', verbose_name='Image principale')),
                ('is_featured', models.BooleanField(default=False, verbose_name='À la une')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta titre')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Réalisation',
                'verbose_name_plural': 'Réalisations',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='Image')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Légende')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texte alternatif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publiée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='portfolio.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Image de galerie',
                'verbose_name_plural': 'Images de galerie',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('profession', models.CharField(blank=True, max_length=200, verbose_name='Profession')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Entreprise')),
                ('message', models.TextField(verbose_name='Message')),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=20, verbose_name='Statut')),
                ('is_featured', models.BooleanField(default=False, verbose_name='À la une')),
                ('admin_note', models.TextField(blank=True, help_text="Notes internes pour l'administrateur", verbose_name='Note admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='portfolio.project', verbose_name='Projet associé')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
