# Generated by Django 6.1 on 2026-09-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='city',
            field=models.CharField(default='Grand Nord ', max_length=100, verbose_name='Ville'),
        ),
    ]
